name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm install

    # Publish to NPM Packages
    - uses: JS-DevTools/npm-publish@v1
      with:
        registry: 'https://registry.npmjs.org/'
        token: ${{ secrets.GITHUB_TOKEN }}

    # Publish to GitHub Packages
    - uses: JS-DevTools/npm-publish@v1
      with:
        registry: 'https://npm.pkg.github.com'
        token: ${{ secrets.GITHUB_TOKEN }}